<?php
?>
<?php
$blockObj= $block->getLayout()->createBlock('DCKAP\AkeneoSync\Block\Adminhtml\ConfigProduct');
$configEnable = $blockObj->getAkeneoConfig();
?>

<div class="akeneo-connector-uploader">
    <div class="akeneo-connector-step">
        <h2><?php echo __('Select import type:') ?></h2>
        <div class="akeneo-connector-types">
            <?php $collection = $block->getCollection() ?>
            <?php /** @var mixed $import */ ?>
            <?php foreach ($collection as $import): ?>
                <?php if ($block->isAllowed($import->getCode())): ?>
                    <div class="import-type" onclick="Akeneo_Connector.type('<?php echo $import->getCode() ?>', this)">
                        <?php echo $import->getName() ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($configEnable) : ?>
            <div class="config-type" >
                <a href="<?= $block->getUrl('akeneosync/parentproduct/index') ?>"  style="padding-left: 12px;">Configurable Product</a>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="akeneo-connector-step step-last">
        <button type="button" class="primary" onclick="Akeneo_Connector.run()">
            <span class="ui-button-text">
                <span><?php echo __('Import') ?></span>
            </span>
        </button>
    </div>
</div>

<ul class="akeneo-connector-console">
    <li class="selected"><?php echo __('Waiting for import...') ?></li>
</ul>

<script>
    require(
        ["Akeneo_Connector/js/akeneo_connector"],
        function (akeneoConnector) {
            akeneoConnector.init('<?php echo $runUrl; ?>', '.akeneo-connector-console');
            window.Akeneo_Connector = akeneoConnector;
        }
    );
</script>
<style>
    .config-type a {
        background-color: #eb5202;
        border-color: #eb5202;
        color: #ffffff;
        text-shadow: 1px 1px 0 rgb(0 0 0 / 25%);
        min-height: 30px;
        width: 170px;
        padding: 5px 5px;
        float: left;
        margin: 0 0.8rem 0.8rem;
        color: #fff;
        font-size: inherit;
        font-weight: 600;
        text-align: center;
    }
    .config-type a:hover {
        text-decoration: none;
    }
</style>
